name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update version
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Bump version to ${{ github.event.release.tag_name }}'
      - name: Build the file
        run: |
          cd /home/runner/work/sip-hass-card/sip-hass-card/
          npm ci
          npm run build
      - name: Upload files to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/sip-hass-card/sip-hass-card/dist/*.js
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
